---
  - name: Config agent groups
    ansible.builtin.copy:
      content: |
        <agent_config>
          <labels>
            <label key="group">{{ item }}</label>
          </labels>
        </agent_config>
      dest: /var/ossec/etc/shared/{{ item }}/agent.conf
      owner: wazuh
      group: wazuh
      mode: '0660'
    loop: "{{ agent_groups }}"
