  - name: Hashing the internal users password
    shell: |
      export JAVA_HOME=/usr/share/wazuh-indexer/jdk
      {{ indexer_sec_plugin_tools_path }}/hash.sh -p '{{ user.password }}'
    register: password_hashed
    no_log: '{{ indexer_nolog_sensible | bool }}'

  - name: Set user password
    replace:
      path: "{{ indexer_sec_plugin_conf_path }}/internal_users.yml"
      regexp: '(?<={{ user.username }}:\n  hash: )(.*)(?=)'
      replace: "{{ password_hash | quote }}"
    vars:
      password_hash: "{{ password_hashed.stdout_lines | last }}"
    no_log: '{{ indexer_nolog_sensible | bool }}'

